services:
  - type: web
    name: exoplanet-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MODEL_PATH
        value: saved_models/stacking_model.pkl
      - key: METADATA_PATH
        value: saved_models/model_metadata.pkl
      - key: MODEL_METADATA_PATH
        value: saved_models/model_metadata.pkl
      - key: LOG_LEVEL
        value: INFO
